---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: ragr
spec:
  encryptedData:
    .dockerconfigjson: AgAcgLJ+MCaFAQu9RTW7syGjzaU6oeV0l51I5M8xiWWnIzx5oL/Z4omuRf+BcgmWPY3neI04ekSru48/9tTUWPa76yQ+kd8dnSr8h9TloB5Rkaaw9B31hepqMYHUt36NBKFqBd5oZz2vD/oM8jp5JMxIU4VHUZ4cy4c0WCXsr7pRy2PFoUf7jM+fPWipZ/nS40zCdWYwIGhv53zJwEnQD9nDlWGfcQyf9G258/HKFBUXVnY+EWFsgYM7zm2Wra/igl4VaVNTanyCX+YDNiUPYFQjawSu2azvWdU2QgbXweRnzh27fuqP6rPhdX6WLpn46AewA/F/AgwftS5atc4cw3+W7YYrhi9CRqOTZIbVCbufqf1cHKzqFhbifMV/hhxPTYGUEWsnG7Ymm49pJ0TfnE0cCi/grmMm78BPKVxFBu3SDbpfwtRpSr+3MwdGqF0PSlhcjXynrTlWdOX9N5ly+MRKXjlb4SmzARVlm4qBNfa+xT8O+Aw+5Ne4ipsUB8C5t/L2cmKN2WyTpDtCXOvjA0kt8ybjrCuHrdNnCfiiVYSn2o/HMgC5VyRgroGJbTHyRs53NsHfQ01cH/EVxGTkRnGKKgF+kSNkvvVq9g6KagqwUBqp/RFcrjpqN12JVdBMIpOJ+Xf/oopdIFCG/uoe3qNZBVgk0QKcgkQswiT7fVOg5R27eh5WeKbUpO5Y8fKFyQOLPT/76vOx0iclsw67g+O2wu3Y0Nhvut/lvPIMUQtNGYT2UXoM2Fi5ZG5elfGPm5Q4E089sDwr0ISJR2LrBcfNG6C2wsE4pZp2Gz11qJ0MFyYGVRJFpWerd+Ce3lNNQ/2tsja6l4Isn8CdZDreVhCzc/AvGrtqjrbxYjk/HnTKEo/ULBhs3YEC0buvSyMZyhvf4tPjg3IlgskhL9TFTvcCmxxMlbyv6iYmhRI9ZoXYNC1bgQ==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: ragr
    type: kubernetes.io/dockerconfigjson
