apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: ragr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-expandable
  resources:
    requests:
      storage: 10Gi
